import PySimpleGUI as sg
import json
from config import *
from ..functions import logicConfigurationScreen as logic_config
      
def abrir_config(nombre_perfil):
    """Procedimiento que especifica las caracteristicas 
    de la ventana configuracion y la devuelve"""
   
    dificultad_seleccionada= logic_config.buscar_dificultad()

    layout=[
        [sg.Push("white"), sg.Text("Configuracion", 
                            font=TITULO2, 
                            text_color=("black"), 
                            background_color=("white"), 
                            pad=((0,0),(0,70))), sg.Push("white")],
        [sg.Text(("Tiempo limite por ronda (Segundos)"), font=OPCIONES, 
                                                    pad=((0,0),(0,20)), 
                                                    background_color=("white"), 
                                                    text_color=("black")), 
                                                    sg.Push("white"), 
                                                    sg.Slider((10,60), 
                                                    orientation="h", 
                                                    size=(30,15), 
                                                    border_width=(3), 
                                                    background_color=("white"), 
                                                    pad=((0,80),(0,20)), 
                                                    text_color=("black"), 
                                                    trough_color=("black"), 
                                                    enable_events=True,
                                                    default_value=(dificultad_seleccionada["tiempo_x_ronda"]), 
                                                    key=("-TIEMPO_X_RONDA-"))],
        [sg.Text(("Cantidad de rondas por juego"), 
                                                    font=OPCIONES, 
                                                    pad=((0,0),(0,20)), 
                                                    background_color=("white"), 
                                                    text_color=("black")), 
                                                    sg.Push("white"), 
                                                    sg.Slider((10,20), 
                                                    orientation="h", 
                                                    size=(30,15), 
                                                    border_width=(3), 
                                                    background_color=("white"), 
                                                    pad=((0,80),(0,20)), 
                                                    text_color=("black"), 
                                                    trough_color=("black"),
                                                    enable_events=True,
                                                    default_value=(dificultad_seleccionada["rondas_x_juego"]), 
                                                    key=("-RONDAS_X_JUEGO-"))],
        [sg.Text(("Puntaje sumado por cada respuesta correcta"), font=OPCIONES, 
                                                    pad=((0,0),(0,20)), 
                                                    background_color=("white"), 
                                                    text_color=("black")), 
                                                    sg.Push("white"), 
                                                    sg.Slider((10,50), 
                                                    resolution=(10),
                                                    orientation="h", 
                                                    size=(30,15), 
                                                    border_width=(3), 
                                                    background_color=("white"), 
                                                    pad=((0,80),(0,20)), 
                                                    text_color=("black"), 
                                                    trough_color=("black"), 
                                                    enable_events=True,
                                                    default_value=(dificultad_seleccionada["suma_puntaje"]), 
                                                    key=("-SUMA_PUNTAJE-"))],
        [sg.Text(("Puntaje restado por cada respuesta incorrecta"),font=OPCIONES,  
                                                    pad=((0,0),(0,20)), 
                                                    background_color=("white"), 
                                                    text_color=("black")), 
                                                    sg.Push("white"), 
                                                    sg.Slider((10,50), 
                                                    resolution=(10),
                                                    orientation="h", 
                                                    size=(30,15), 
                                                    border_width=(3), 
                                                    background_color=("white"), 
                                                    pad=((0,80),(0,20)), 
                                                    text_color=("black"), 
                                                    trough_color=("black"), 
                                                    enable_events=True,
                                                    default_value=(dificultad_seleccionada["resta_puntaje"]), 
                                                    key=("-RESTA_PUNTAJE-"))],
        [sg.Text(("Características a mostrar"),font=OPCIONES,  
                                                    pad=((0,0),(0,20)), 
                                                    background_color=("white"), 
                                                    text_color=("black")), 
                                                    sg.Push("white"), 
                                                    sg.Slider((1,5), 
                                                    orientation="h", 
                                                    size=(30,15), 
                                                    border_width=(3), 
                                                    background_color=("white"), 
                                                    pad=((0,80),(0,20)), 
                                                    text_color=("black"), 
                                                    trough_color=("black"), 
                                                    enable_events=True,
                                                    default_value=(dificultad_seleccionada["car_a_mostrar"]), 
                                                    key=("-CAR_A_MOSTRAR-"))],
        [sg.Button("Volver", font=OPCIONES, 
                            button_color=("black", "white"), 
                            border_width=(3),
                            key="-CONFIG_VOLVER-"),
        sg.Button("Guardar", font=OPCIONES, 
                            button_color=("black", "white"), 
                            border_width=(3),
                            key="-GUARDAR-"), sg.Push("white")],

    ]
    return sg.Window("FiguRace (Configuración)", 
        layout,
        size=(1500,1500), 
        border_depth=(1),
        location=(-10,0), 
        margins=(60,60), 
        background_color=("white"), 
        finalize=True)
    